# https://www.youtube.com/watch?v=nSdzAcCXLxE
kind: Namespace
apiVersion: v1
metadata:
  name: gemini

# Gemini es una herramientas para manejar backups de PVC desde kubernetes.
# Si bien es posible hacer un snapshots desde las plataformas cloud (AWS, Digital Ocean, etc.) pero al hacerlo por kubernetes
# Nos aseguramos de que quede igual en todos los clusters

# Chocolatey
# Es un gestor de paquetes para Windows, que nos permite instalar software cómodamente desde la consola y mantener el software actualizado.
  # https://desarrolloweb.com/home/chocolatey#:~:text=Para%20instalar%20Chocolatey%20necesitamos%20acceder,install%20y%20seguir%20las%20instrucciones.&text=Si%20obtenemos%20una%20salida%20indicando,tenemos%20que%20hacer%20nada%20m%C3%A1s.
# Instalación:
# Correr una ventana de PowerShell en modo superusuario y posteriormente ejecutar los siguientes comandos:
# Get-ExecutionPolicy
# Set-ExecutionPolicy AllSigned
# Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))


# Helms es el manejador de paquetes para Kubernetes, es como un apt-get.
# Se baja un paquete con los servicios o dependencias para instalar en nuestro cluster de kubernetes.
# Instalación:
# En la ventana de PowerShell con privilegios de administrador es necesario correr: choco install kubernetes-helm 

# Particularmente para Gemini, necesita muchos componentes que se encuentran en el CDR de Kubernetes, éstos no vienen instalados
# en la instalación, valga la redundancia, que uno realiza por defecto. Éste CDR de kubernetes además de brindarme un canal para bajar estas dependencias,
# tambien me permite crear componentes.

# Fuente: https://www.fairwinds.com/news/fairwinds-introduces-gemini-open-source-tool-automates-backup-and-restoration-of-persistentvolumes-in-kubernetes

# Instalación:
# helm repo add fairwinds-stable https://charts.fairwinds.com/stable
# 