apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: pvc
spec:
  accessModes:
  - ReadWriteOnce # Permisos que tiene
  resources:
    requests:
      storage: 1Gi # Tamaño de la porcion de disco
  #  Libreria que usa kubernetes para conectarse a la API de nuestro proveedor, en nuestro caso es Digital Ocean y crear el volumen
  storageClassName: do-block-storage 

