# https://www.youtube.com/watch?v=fhYSKEy0s8w Tutorial para crear un clúster en Digital Ocean
kind: Namespace
apiVersion: v1
metadata:
  name: test
# Son pequeñas porciones de cluster donde podemos limitar la visibilidad entre sí para tener encapsulamiento si así lo deseamos
# Una buena practica es tener todo bajo namespace, es más facil identificarlos y administrarlos
# Aplicar los cambios de un archivo .yaml:
  # kubectl apply -f . #  De esta forma ejecuto todos los archivos .yaml que se encuentren dentro del directorio
  # kubectl apply -f .\00.namespace.yaml # De esta forma sólo ejecuto el archivo .yaml indicado
  # Para eliminar un namespace:
    # kubectl delete namespace nombre
  # Si al momento de correr un comando no coloco el namespace, por defecto, kubernetes ejecuta en el namespace llamado default
  # Para correr un comando dentro de un namespace:
    # kubectl -n test apply -f archivo.yaml

# Nodos: Es donde corren los controladores
# Servicios: La forma de acceder a los pods
# Pods: Set de contenedores donde corren la aplicación, generalmente es uno pero pueden ser más.