apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  # namespace: hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      role: php-apache
  template:
    metadata:
      labels:
        role: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "20m"

# Averiguo la IP Externa del nodo y peticiono a través del navegador con el puerto 30000, en principio tendra la pantalla de bienvenida de nginx.
# Posteriormente un mensaje de "OK!" de que la imagen se ejecuto correctamente.