apiVersion: v1
kind: Pod
metadata:
  name: nginx-02
  namespace: downward
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /etc/podinfo # Crea un directorio en cada uno de los pods que tendran como contenido lo que almacene la API de kubernetes
      name: podinfo
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"

  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels" # Un ejemplo de uso de esta herramienta, podria ser para pasar info del host a los pods, como puede ser la IP o ciertos datos puntuales (solicitudes, limits de memoria, nombre de pods, etc.)
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
