#cloud-config
# Documento acerca de este lenguaje:
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
package_update: true
packages:
  - docker.io # Instala docker en la instancia
write_files:
  - path: /root/index.html # Crea un archivo con el contenido
    content: |
      Sos un capo de terraform
runcmd:
  - cd /root
  - docker run -d -v /root/index.html:/usr/share/nginx/html/index.html -p 80:80 nginx # nginx es el nombre de la imagen
  # Monta el volumen donde esta el archivo creado anteriormente para que cuando corra el contenedor lo muestre en lugar del archivo que viene por defecto

# Es IMPRECINDIBLE que la primer linea no se modifique, forma parte de la sintaxis del archivo