# https://youtu.be/0iMEcrcfG5A?t=252
apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  namespace: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    role: wordpress
# Eliminamos el nodo y al crear uno nuevo (con diferente nombre e IP) levanta dentro del él el nuevo nodo.
# Toda la metadata, definición de servicios y contenedores que queremos correr se almacenan en las BD de las controladores de kubernetes (ETCD)
# Por lo que se deberia mantener la misma IP, pods tal y como lo teniamos antes.