apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: jobs-and-cronjobs
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  # backoffLimit: 4 bandeja que establece un número de intentos en el caso de que la creación del job falle
