apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: jobs-and-cronjobs
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo "Hola Adrian, soy un cronjob"
          restartPolicy: OnFailure