apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  namespace: liveness
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox # Linux de funciones reducidas
    resources:
      limits:
        memory: "64Mi"
        cpu: "10m"
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600 #  Un mecanismo para hacer el check es preguntar por un fichero
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
