apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: readiness
  labels:
    app: nginx # Esta linea es importante porque el servicio de nginx creado se enlaza a través de esta etiqueta, permitiendo así que cuando peticionemos el servicio de nginx con la IP del nodo:30000, esta solicitud pueda redirigirse hacia el check a la ruta de la linea 20
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "64Mi"
        cpu: "10m"
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: / # Se hace una petición al raiz a través del puerto 80 para que nginx nos diga si esta listo para recibir solicitudes
        port: 80 
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80 # Solamente chequea que el puerto 80 este levantado
      initialDelaySeconds: 15
      periodSeconds: 20
