apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: readiness
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: nginx
