apiVersion: v1
kind: Service
metadata:
  name: lojack-svc
  namespace: lojack
spec:
  type: NodePort
  selector:
    role: sfintegracionapi
  ports:
  - port: 80
    targetPort: 80 # Puerto que va a correr el contenedor
    nodePort: 30000 # Puerto que va a correr en el nodo y que va a puntar al puerto 80 del contenedor
# Este tipo de servicio crea un puerto en el worker que apunta al contenedor que nosotros creemos.

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
#https://docs.microsoft.com/es-mx/visualstudio/containers/container-build?WT.mc_id=visualstudio_containers_aka_containerfastmode&view=vs-2022