apiVersion: v1
kind: Pod
metadata:
  name: nginx-lp
  namespace: pod-priorities
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1000m"
  priorityClassName: low-priority
