apiVersion: v1
kind: Pod
metadata:
  name: nginx-hp-non-preemptive
  namespace: pod-priorities
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "100m"
  priorityClassName: high-priority-nonpreemptive