apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
  # namespace: pod-priorities No estan atadas a un namespace sino a un clúster completo
value: 1000000
preemptionPolicy: PreemptLowerPriority # Si existe un pod con prioridad en pending, sacara a un pod con menos prioridad del estado running para correr el pod en cuestión
globalDefault: false
description: "This priority class should be used for high-priority service pods only."

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-nonpreemptive
value: 1000000
preemptionPolicy: Never # No reemplaza
globalDefault: false
description: "This priority class should be used for high-priority service pods only."

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 500000
globalDefault: true # Cualquier pod que no tenga ninguna prioridad definida se le asignara ésta por defecto
description: "This priority class should be used for low-priority service pods only."